### ISSUE TITLE
Run with c302 - "Generating images for neuronal activity" error

### ISSUE THREAD

**Issue by lungd** [openworm/sibernetic#116]
I can run sibernetic with NEURON bridge.
Running with c302 "python sibernetic_c302.py" gives me following error:

Sib_c302  >>> 
Sib_c302  >>> ************************************************************************
Sib_c302  >>> *
Sib_c302  >>> *  Generating images for neuronal activity...
Sib_c302  >>> *
Sib_c302  >>> ************************************************************************
Traceback (most recent call last):
  File "sibernetic_c302.py", line 253, in <module>
    main()
  File "sibernetic_c302.py", line 70, in main
    run(a=args)
  File "sibernetic_c302.py", line 227, in run
    verbose=True)
  File "/usr/local/lib/python2.7/dist-packages/pyNeuroML-0.2.2-py2.7.egg/pyneuroml/pynml.py", line 578, in reload_saved_data
    'file %s' % file_name))
OSError: Could not find simulation output file /home/developer/openworm/sibernetic/NeuroML2/results/c302_C1_Muscles.dat
root@9793801e23f3:/home/developer/openworm/sibernetic# echo $PYTHONPATH 
./sibernetic_NEURON:./src:./CElegansNeuroML/CElegans/pythonScripts/c302:./src
root@9793801e23f3:/home/developer/openworm/sibernetic#

**Comment by skhayrulin** [comment]
@pgleeson I've just clone CElegansNeuroML but I can't find sibernetic_c302.py am I right that this file should be in CElegansNeuroML/CElegans/pythonScripts/c302 folder?

**Comment by lungd** [comment]
@skhayrulin, @pgleeson  I had cloned sibernetic_NEURON and CElegansNeuroML outside sibernetic with absolute paths in PYTHONPATH.
Whether with the projects inside or outside sibernetic, I get the same error.

**Comment by lungd** [comment]
@skhayrulin, sibernetic_c302.py is inside sibernetic/

**Comment by skhayrulin** [comment]
@lungd thanks!

**Comment by lungd** [comment]
The generated LEMS_c302_nrn.py file should get executed inside sibernetic_c302.py?
I've added:
```
from subprocess import call 
call(["python", "%s/LEMS_c302_nrn.py" % sim_dir])
```
below main_nrn_py.close().

That gave me an "integer division or modulo by zero" error (sibernetic_c302.py:189)
I think the duration var inside the DEFAULTS dict should be in msec so I've changed it from 1.0 to 1000. Now it is still running

**Comment by pgleeson** [comment]
No @lungd the LEMS_c302_nrn.py is initialised and run from inside Sibernetic using calls to the Python class in the same way as the sine generator was used. 

Can you run:
    
     python sibernetic_c302.py -duration 0.1 > report

on the unaltered code and send me/pastebin the full log?

**Comment by lungd** [comment]
root@9793801e23f3:/home/developer/openworm/sibernetic# python sibernetic_c302.py -duration 0.1 > report
Traceback (most recent call last):
  File "sibernetic_c302.py", line 253, in <module>
    main()
  File "sibernetic_c302.py", line 70, in main
    run(a=args)
  File "sibernetic_c302.py", line 227, in run
    verbose=True)
  File "/usr/local/lib/python2.7/dist-packages/pyNeuroML-0.2.2-py2.7.egg/pyneuroml/pynml.py", line 578, in reload_saved_data
    'file %s' % file_name))
OSError: Could not find simulation output file /home/developer/openworm/sibernetic/NeuroML2/results/c302_C1_Muscles.dat

report: http://pastebin.com/nXuePBa1

**Comment by pgleeson** [comment]
@lungd It looks like c302 is properly installed and getting generated correctly. The issue is that the generated Nrn code isn't being used by Sibernetic inside the simulation. Have you run

    make clean
    make

after you pulled the latest changes from Sibernetic?

**Comment by lungd** [comment]
I forgot to rebuild sibernetic. Thank you for the hint @pgleeson.
Now I get
```
root@7f6850368e95:/home/developer/openworm/sibernetic# python sibernetic_c302.py -duration 0.1 > err_report
Traceback (most recent call last):
  File "sibernetic_c302.py", line 253, in <module>
    main()
  File "sibernetic_c302.py", line 70, in main
    run(a=args)
  File "sibernetic_c302.py", line 245, in run
    plot_positions(pos_file_name,rate_to_plot = int(a.duration/5))
  File "/home/developer/openworm/sibernetic/src/plot_positions.py", line 76, in plot_positions
    plot_frame = (frame%rate_to_plot == 0)
ZeroDivisionError: integer division or modulo by zero
```
Full log: https://paste.ee/p/ufWhq

**Comment by pgleeson** [comment]
That's just an error plotting the body shape at the end and may be to do with running the simulation too short a time. Try removing  -duration 0.1

**Comment by lungd** [comment]
I get the same error without -duration

**Comment by lungd** [comment]
Calling sibernetic_c302 without arguments leads to a duration of 1.0 ?
sibernetic_c302 calls plot_positions using rate_to_plot=int(duration / 5). int(1.0/5) = 0
https://github.com/openworm/sibernetic/blob/development/sibernetic_c302.py#L245

Inside plot_positions there is a modulo "frame % rate_to_plot". 0%0 -> ZeroDivisionError
https://github.com/openworm/sibernetic/blob/development/src/plot_positions.py#L76

**Comment by pgleeson** [comment]
You could just manually change rate_to_plot to 10 or 20 or take out that line altogether. It was a last minute change to scale the number of worm images in the figure by the duration...

Note the other files generated by the simulation should have been successfully saved in a folder under simulations/

**Comment by lungd** [comment]
Ty again @pgleeson 
I close this issue now because the ZeroDivisionError is not related to the generation of images.

**Comment by pgleeson** [comment]
Ok @lungd, so I assume you got it all running then. 

Did you by any chance try it with your tap withdrawal circuit?
