### ISSUE TITLE
Tests not working on latest commit

### ISSUE THREAD

**Issue by slarson** [openworm/sibernetic#124]
From @pgleeson:

Running tests with "./Release/Sibernetic -test" used to pass, now fails, complaining of "Couldn't create file check the file name: ./logs/total_energy_distrib.txt". I create the logs directory, but still it has a segmentation fault

**Comment by a-palyanov** [comment]
Thanks for pointing at this. Not a big problem, I'll fix it soon (it was not because of my update, I didn't touched anything connected with tests).

**Comment by a-palyanov** [comment]
Fixed in the recent update (of development branch).
