### ISSUE TITLE
Muscle activation should be set only by the Python class 

### ISSUE THREAD

**Issue by pgleeson** [openworm/sibernetic#129]
There is currently some hard coding of the activation signals at https://github.com/openworm/sibernetic/blob/development/src/owPhysicsFluidSimulator.cpp#L417.

The muscle signals coming in should be only set by the python class supplied to drive the muscles, either [MuscleSimulation](https://github.com/openworm/sibernetic/blob/development/main_sim.py#L93) or C302NRNSimulation.

See commit below for fix. PR soon...

**Comment by pgleeson** [comment]
FYI @a-palyanov I've added the "smooth start" to the MuscleSimulation Python class here:
https://github.com/pgleeson/sibernetic/commit/e7e17489485f056c53418bd6ae8cf4ddaaf5c3c6#diff-1ae43b765dbe328a71a4d401b9f30771R79

Can be plotted with: python main_sim.py

![selection_390](https://user-images.githubusercontent.com/1556687/31793544-6f1a10ba-b517-11e7-9167-0594b2a294ef.png)

**Comment by a-palyanov** [comment]
Yes, there is actually some hard coding to achieve more realistic shapes of the body while swimming and crawling. There are two transformation of the signal: 1) sin(...)+1 --> (sin(...)+1)^2 to reduce the number of worm body segments at which both left and right muscles contract simultaneously, causing body shortening, and 2) attenuation of the signal for the muscles which are close to the tail (the closer the stronger), which a somehow compensates the fact that muscle cells near the head are shorter then those at the tail, which in turn causes worm body shapes not very close to real worm's.
And the smooth start, which you've mentioned, as well.
I'll remove all this from the code, but in this case something like this should be inserted into main_sim.py

**Comment by a-palyanov** [comment]
Fixed in the recent update (of development branch).

**Comment by pgleeson** [comment]
@a-palyanov Can you confirm that it was intended to change the behaviour of the sine wave input to swimming -> crawling? 

![selection_429](https://user-images.githubusercontent.com/1556687/32374927-a1a2951c-c097-11e7-85f9-170fd2601ca1.png)

This is fine if you're mainly testing/tuning swimming behaviour at the moment, but when the worm_alone is run, it quickly bends to a C shape. 

It should be quite straight forward to have multiple Python classes in main_sim.py for injecting sinusoidal (or any other) activation patterns, and these could be set at the command line (as c302 is, see https://github.com/pgleeson/sibernetic/blob/development/inc/owConfigProperty.h#L219), or specified in the configuration file. It would be much easier for others to test/plot/add them then.

**Comment by a-palyanov** [comment]
@pgleeson Both swimming and crawling look more natural when I use not a pure sin signal, but rather a  (sin(...)+1)^2. Additionally, different environments require different maximal muscle contraction force, and the real C. elegans is able to adjust it if necessary. Worm_alone for sure requires noticeably lower maximal muscle contraction force, so when it is used with muscle activating signals for swimming it causes the body to bend to a C chape.
I agree that to have multiple Python classes for different locomotion types is a good idea and hope that there will be an opportunity to implement it in some near future.

**Comment by slarson** [comment]
I think this got incorporated; re-open if not...
