### ISSUE TITLE
Pressure file format issue

### ISSUE THREAD

**Issue by pgleeson** [openworm/sibernetic#146]
When a simulation is run with:

    ./Release/Sibernetic  -f  worm_alone_half_resolution  -no_g -l_to  timelimit=0.0001 timestep=5e-06 logstep=10 device=ALL

it saves a file with the pressure values in file buffers/pressure_buffer.txt. As expected the pressure values for 2 times are saved, for 2285 points on the worm surface. 

However the saved info for the points show:

```
[Iteration 0]
Particle:	0
	Position:	51.1166	5.21027	13.3002	2.105
	Pressure:	-nan
Particle:	1
	Position:	49.0494	5.20471	13.307	2.105
	Pressure:	-nan
Particle:	2
	Position:	50.0918	6.23142	13.3	2.105
	Pressure:	-nan
...
```
for the first iteration/timepoint and 
```
[Iteration 10]
Particle:	0
	Position:	-nan	-nan	-nan	2.105
	Pressure:	-nan
Particle:	1
	Position:	-nan	-nan	-nan	2.105
	Pressure:	-nan
Particle:	2
	Position:	-nan	-nan	-nan	2.105
	Pressure:	-nan
...
```
for the second.

**Comment by lungd** [comment]
@pgleeson @skhayrulin I think we can close this issue?

**Comment by pgleeson** [comment]
Sure, looks to be fixed!
