### ISSUE TITLE
Double text in README

### ISSUE THREAD

**Issue by pgleeson** [openworm/sibernetic#153]
@skhayrulin This commit of yours seems to have cut and paste multiple copies of some sections in the README: https://github.com/openworm/sibernetic/commit/4c29d5f8e1687dea591d41d640d02881777a5e4f#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by nuragicboy** [comment]
I can fix this

**Comment by gidili** [comment]
@nuragicboy feel free to open a PR! 🙏

**Comment by nuragicboy** [comment]
I think i'm done.
The whole readme was duplicated from around line 200, I kept the spelling corrections, that were spread among the 2 copies

**Comment by pgleeson** [comment]
Done
