### ISSUE TITLE
Following OpenCL technology progress: 

### ISSUE THREAD

**Issue by a-palyanov** [openworm/sibernetic#47]
Hi guys,
recently I came across the following information:
(http://en.wikipedia.org/wiki/OpenCL#OpenCL_1.2)
"OpenCL 2.0. On November 18, 2013, the Khronos Group announced the ratification and public release of the finalized OpenCL 2.0 specification. Updates and additions to OpenCL 2.0 include:

   Shared Virtual Memory
   Nested Parallelism
   Generic Address Space
   Images
   C11 Atomics
   Pipes
   Android Installable Client Driver Extension
   Industry Support"

About hardware supporting OpenCL 2.0:
(http://stackoverflow.com/questions/23745612/hardware-supporting-opencl-2-0)
"At present, there are no conformant implementations of OpenCL 2.0 available.

In terms of hardware support, AMD have stated that some of their latest GPUs have the capabilities for OpenCL 2.0, and I would expect that most (if not all) modern CPUs have too (Xeon Phi likely does as well). NVIDIA's latest GPUs are probably also compliant, since they have CUDA equivalents of nested parallelism and SVM.

So, we are just waiting for the actual implementations (i.e. drivers) to appear. At IWOCL'14 last week it was mentioned that the conformance package for OpenCL 2.0 was only just finalised recently, so we can expect to see these implementations start to appear in the coming months.

In the meantime, AMD have preliminary support for some OpenCL 2.0 already available in their latest beta driver."

**Comment by slarson** [comment]
@a-palyanov what ever happened with this? :)

**Comment by a-palyanov** [comment]
@slarson Here is a list of devices which support OpenCL 2.0:
https://www.khronos.org/conformance/adopters/conformant-products#opencl

Our R290X in in the list, but it requires (as well as all other devices) Windows 8.1 64 bit.
