### ISSUE TITLE
Add info on command line options available when Sibernetic run with -help

### ISSUE THREAD

**Issue by pgleeson** [openworm/sibernetic#59]
Working on this here: https://github.com/pgleeson/Smoothed-Particle-Hydrodynamics/blob/WormBodySimulation/src/main.cpp#L61

Example of current output:

    Sibernetic
      This is a C++ implementation of the Contractile SPH (Electrofluid) algorithm applied to C. elegans locomotion
        Usage:  ./Release/Sibernetic [OPTION]
       -no_g       Run without graphics
       -l_to       Save simulation results to disk
       -l_from     Load simulation results from disk
       -test       Run some tests
       -help       Print this information

Comments & suggestions welcome @skhayrulin, @a-palyanov

**Comment by skhayrulin** [comment]
Hi @pgleeson
I'm planning to include this enhancement into current code of Sibernetic in development branch could you please make pull request if everything is ready to be merged?

**Comment by pgleeson** [comment]
Ok, need to check my local copy, I have a number of modifications including this. Does the development branch use the WormBodySimulation as default, I was working in that branch? Last time I looked that was using the falling cube.

Actually, would it be straightforward to switch between the test cube and the worm body sim using a command line option, i.e. so all updates get reflected on the development branch?

**Comment by skhayrulin** [comment]
* Does the development branch use the WormBodySimulation as default, I was working in that branch? 

Please make pull request in WormBodySimulation branch, for now in development branch no worm code. 

* Actually, would it be straightforward to switch between the test cube and the worm body sim using a command line option, i.e. so all updates get reflected on the development branch?

I'm planning to add worm config in development branch ASAP, you're right it will be more useful actually I'm planning log worm configuration into configuration file and load it when needed worm body simulation. I hope to finished with it on next week I'll let you know

**Comment by pgleeson** [comment]
See #63

**Comment by skhayrulin** [comment]
@pgleeson I just want to noticed you that I've finished with big update of Sibernetic code.
 * I added possibility to make snapshot of current configuration just press 's' when run Sibernetic
 * I merged all updates from WormBodySimulation branch into development branch. I recommend you to work with development branch for now. For run worm simulation you just need run this ./Release/Sibernetic -f worm
 * As you understood key -f is indicate that we ask Sibernetic run configuration from config file
 * Also I've just updated <a href="https://github.com/openworm/sibernetic/blob/development/README.md">README.md</a> file you can find all updates there in section  <a href="https://github.com/openworm/sibernetic/blob/development/README.md#main-command-options">from this</a> <a href="https://github.com/openworm/sibernetic/blob/development/README.md#configuration-file-format"> to this</a>

And I want to ask you could you please check english in that sections :)

**Comment by pgleeson** [comment]
Thanks @skhayrulin, looks like a great update. Works fine on my machine, and even intermittent problem with the worm blowing up seem to have stopped. Will be 1-2 weeks before I have time for a detailed look, but will certainly make more updates to development & make pull requests.
