### ISSUE TITLE
From time to time appearing strange behaviour 

### ISSUE THREAD

**Issue by skhayrulin** [openworm/sibernetic#60]
Sometime Sibernetc shows strange behaviour when start: explosion, fluctuation of springs etc. Looks like race condition somewhere.
- [x] make branch for this bug
- [x] log and compare data for bug and nobug run
- [ ] understood why strange values in acceleration is appearing
should be like this
![screenshot from 2015-03-26 12 39 51](https://cloud.githubusercontent.com/assets/1581992/6841475/23411b82-d3ad-11e4-8020-58f25bcd75db.png)
but sometimes it looks like this:
![bug](https://cloud.githubusercontent.com/assets/1581992/6841482/3a188a98-d3ad-11e4-9f69-3fae03359db4.png)

**Comment by ignotur** [comment]
What do you color-coded as blue dots which still inside the box in  wrong simulation?

**Comment by skhayrulin** [comment]
blue it's a water particles, black is a elastic particles, red lines are elastic connections, meanwhile blue triangles are membranes.

**Comment by skhayrulin** [comment]
branch for this bug is <a href="https://github.com/openworm/Smoothed-Particle-Hydrodynamics/tree/fixBug_%2360">here</a>

**Comment by ignotur** [comment]
I have started the program more than 30 times and I didn't manage to catch this bug. All times the cube in the centre formed a sphere and then it started to fall down.

**Comment by skhayrulin** [comment]
What is you OpenCL device and what version of OpenCL driver do you use? Actually I saw this problem not only on my machine as I remember @pgleeson and @a-palyanov had the same problem on their machines.

**Comment by pgleeson** [comment]
My info: 
CL_PLATFORM_VERSION [0]: 	OpenCL 1.2 AMD-APP (1214.3)
CL_CONTEXT_PLATFORM [0]: CL_DEVICE_NAME [0]:	Intel(R) Core(TM) i7 CPU       M 620  @ 2.67GHz

I sometimes get:

![selection_633](https://cloud.githubusercontent.com/assets/1556687/6966195/14f45ede-d94f-11e4-9415-49812d936687.jpg)

![selection_634](https://cloud.githubusercontent.com/assets/1556687/6966201/1b18874a-d94f-11e4-9b30-b44424d0936e.jpg)

**Comment by ignotur** [comment]
Could you please be more specific. Sometimes is one out of 10 runs or less frequent?

**Comment by pgleeson** [comment]
Worked fine first time I ran Sibernetic today, is happening every time I run it now. Generally a restart resolves the problem. Haven't looked into this in a while...

**Comment by skhayrulin** [comment]
On my machine it happen from time to time I can't make any predictions when or calculate frequency. After some research I can say that probably the problem is in elastic force calculation kernel <a href="https://github.com/openworm/Smoothed-Particle-Hydrodynamics/blob/development/src/sphFluid.cl#L616-L678">here</a> especially in this <a href="https://github.com/openworm/Smoothed-Particle-Hydrodynamics/blob/development/src/sphFluid.cl#L663">line</a>, somehow in first iteration when it's calculating impact of elastic force into acceleration there are big numbers is appearing and acceleration becomes too big and leads to explosion finally. So we need find where and why this numbers is appearing. I'll try to publish more info about my research tomorrow.

**Comment by ignotur** [comment]
Ok, at the first glance for me it seems unavoidable that sometimes this condition is not enough if(r_ij!=0.f). 
Probably it is better to write if (abs(r_ij) > some_small_number)
What do you think?

**Comment by skhayrulin** [comment]
I think that it doesn't explain why explosion happens actually I didn't see too small value of r_ij when I debugged a code. And you can see that r_ij is needed only for normalization of vector vect_r_ij, sorry may be it's not obvious we use <a href="https://github.com/openworm/Smoothed-Particle-Hydrodynamics/blob/development/src/sphFluid.cl#L663">here</a> specific OpenCL objects vector (float4) so vect_r_ij/r_ij means delete each component off vector on scalar r_ij. If yo want I can help you with introduction in OpenCL.

**Comment by skhayrulin** [comment]
I made two experiments description: I took two run one is correct (without explosion) and incorrect, log info can see <a href="https://github.com/openworm/Smoothed-Particle-Hydrodynamics/blob/fixBug_%2360/src/sphFluid.cl#L680-L695">here</a>, also I comment <a href="https://github.com/openworm/Smoothed-Particle-Hydrodynamics/blob/fixBug_%2360/src/sphFluid.cl#L691">line</a> and I also have two run. Actually I also saw an explosion for second experiment from what I can say that problem not in elastic force calculation but in something else. You can see logs belong I compare right run with wrong analogs on first picture <a href="https://github.com/openworm/Smoothed-Particle-Hydrodynamics/blob/fixBug_%2360/src/sphFluid.cl#L691">line</a> is on in second it's off.
![right_vs_wrong_acc_changing](https://cloud.githubusercontent.com/assets/1581992/7004095/6ec9466c-dc7f-11e4-883b-1c4f36f4f6a3.png)

![correct_vs_no_acc_nochanging](https://cloud.githubusercontent.com/assets/1581992/7004099/740c20b8-dc7f-11e4-85e8-f5d853487d30.png)
So you can see that after first iteration of do while cycle everything is allright but on next step some strange value in acceleration[id] is appearing. Last code at the repo. I'm still working on it
