### ISSUE TITLE
Create a configuration file for the worm without external liquid

### ISSUE THREAD

**Issue by pgleeson** [openworm/sibernetic#79]
@skhayrulin would it just be a case of copying https://github.com/openworm/sibernetic/blob/development/configuration/worm and removing the positions of external water particles? How can these be identified in the current file?

Motivation for this is testing the worm sim with different inputs in the absence of liquid, which may speed up the simulation and demonstrate overall worm body behaviour (does it wiggle...) with fewer particles...

**Comment by skhayrulin** [comment]
@pgleeson I've just added configuration file without water in [configuration folder](https://github.com/openworm/sibernetic/tree/development/configuration) name is worm_no_water

**Comment by pgleeson** [comment]
Great, thanks! It's definitely speeded things up. However, the activation doesn't seem to be going into the muscles in this version. Maybe by default if there's any mention of 'worm' in the configuration file name then try to add the contractions?

**Comment by skhayrulin** [comment]
@pgleeson you're right sorry forgot about this and now have no ability to fix it. You should change this lines [70](https://github.com/openworm/sibernetic/blob/development/inc/owConfigProperty.h#L70) and [122](https://github.com/openworm/sibernetic/blob/development/inc/owConfigProperty.h#L122) add addition condition in **if** statement 
```
if(configFileName == "worm" && configFileName == "worm_no_water")
```
in both lines

**Comment by a-palyanov** [comment]
@skhayrulin, are you sure about '&&'? maybe '||'?

Line 70 also should be modified:
'bool isWormConfig(){ return (configFileName == "worm" )? true:false;'
should become 
'bool isWormConfig(){ return (configFileName == "worm" || configFileName == "worm_no_water")? true:false;'

After this it works correctly.

**Comment by skhayrulin** [comment]
@a-palyanov yes you right || not &&

**Comment by skhayrulin** [comment]
Guys I've updated the code it in repository now

**Comment by pgleeson** [comment]
Works great for me now, thanks!
