### ISSUE TITLE
Reloading saved simulations with -l_from

### ISSUE THREAD

**Issue by pgleeson** [openworm/sibernetic#82]
It's great to be able to save and replay simulations with -l_from and -l_to. A few minor suggestions to improve the interactivity of this:

- [ ] At the end of a reloaded/replayed simulation, don't quit the GUI, keep it open and allow the final scene to be viewed/rotated
- [x] Allow the loaded simulation to be replayed from the start (by pressing 'r'), in addition to pausing ('s')
- [x] Allow a configurable number of steps between save points (currently 10 I believe), e.g. with option saveevery=10

**Comment by skhayrulin** [comment]
Add option logstep=N, which makes possible log config every N steps in -l_to mode

**Comment by slarson** [comment]
I believe this is done, no?  Re-open if not.
