### ISSUE TITLE
Memory Leak when run Sibernetic with worm config 

### ISSUE THREAD

**Issue by skhayrulin** [openworm/sibernetic#87]
When run sibernetic with worm config (./Release/Sibernetic -f worm) memory leak is appearing.

**Comment by 0wnrepo** [comment]
I still see this with the current code.
Sibernetic(37527,0x7fff76820300) malloc: *** error for object 0xc000000000000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by skhayrulin** [comment]
@0wnrepo could you please give more info: 
1) on which arch you run sibernetic
2) do you see memory leakage 
3) how much iteration is sibernetic run before crashing?
