### ISSUE TITLE
Enable command line input for several parameters

### ISSUE THREAD

**Issue by slarson** [openworm/sibernetic#88]
- [x] Path that the output files get saved to
- [ ] Muscle force (per single muscle fiber)
- [ ] Viscosity (liquid within body)
- [ ] Viscosity (liquid outside body)
- [ ] Coefficient of friction between particle types
- [ ] Elasticity coefficient

**Comment by skhayrulin** [comment]
@slarson in this [commit])(https://github.com/openworm/sibernetic/commit/de37b75b565cc2d50c56cb51a9171940b383c132) I've added option for indication of location OpenCL program file. When @a-palyanov model will be ready we generate several ocl files for each one.

**Comment by slarson** [comment]
Sounds like we've added the option, now we just need to add the documentation (#95) and then we can close this.

**Comment by slarson** [comment]
For now, these are just going to be built into the .cl files; so we'll just use a switch to point at different .cl files as needed.
