### ISSUE TITLE
Update documentation to include command line parameter to change OpenCL file

### ISSUE THREAD

**Issue by slarson** [openworm/sibernetic#95]
In the creation of #88, it looks like there has been an option implemented to change the OpenCL file.  This issue is to add that to the documentation so we know how to use it.

**Comment by skhayrulin** [comment]
done see here [Main command options](https://github.com/openworm/sibernetic#main-command-options) option name is oclsourcepath you're just need the path to file with ocl program

**Comment by slarson** [comment]
OK great.  In terms of examples, what files that are checked in can I use to test with?  I only see an sphFluid.cl in the src directory.  Are there others?

**Comment by skhayrulin** [comment]
Not yet @slarson but I'll add when merge Andrey code

**Comment by slarson** [comment]
OK great-- those examples will help the docs (and me!) so that everyone
will be able to actually use the option.
ᐧ

**Comment by skhayrulin** [comment]
@slarson I've updated [Run simulation from configuration file section](https://github.com/openworm/sibernetic#run-simulation-from-configuration-file) added information how to run sibernetic with crawling/swimming worm configuration.

**Comment by slarson** [comment]
This is done
