### ISSUE TITLE
Make option settings file

### ISSUE THREAD

**Issue by skhayrulin** [openworm/sibernetic#97]
Add ability to run sibernetic with option file
format:

```
option1=<value>
option2=<value>
option3=<value>
```

**Comment by slarson** [comment]
@skhayrulin did we do this or is this still something we want to do?

**Comment by skhayrulin** [comment]
@slarson actually I think it will be useful in future I mean that number of input arguments is always increasing and this is boring to print it all the time. Now this in progress but I think to move that in other milestone
